### ISSUE TITLE
web cam

### ISSUE THREAD

**Issue by bbartling** [DoganK01/Yolov7-Close-People-Counter#1]
Hi,

If I wanted to experiment with your code on a usb cam and your models would I just use `detect.py`?

If I run I think its index zero that I found with this:

```
import cv2
import numpy as np

all_camera_idx_available = []

for camera_idx in range(10):
    cap = cv2.VideoCapture(camera_idx)
    if cap.isOpened():
        print(f'Camera index available: {camera_idx}')
        all_camera_idx_available.append(camera_idx)
        cap.release()
```

And other computer vision projects I can run with this:

```
from imutils.video import VideoStream

vs = VideoStream(src=args["index"]).start()
```

Thanks for any tips I am not a computer vision person more of a hobbyist in this arena so any help greatly appreciated...

**Comment by bbartling** [comment]
I actually got this to work on Windows 10....pip install -r requirements worked just fine

But I had to update Numpy to numpy-1.23.3 to avoid some error:
```
img = torch.from_numpy(img).to(device)
RuntimeError: Numpy is not available
```

Unfortunate thing at the moment is Windows OS is all I have to work with....but the bus picture rendered OK:

```
py detect.py --weights /content/Yolov7-Close-People-Counter/weights/yolov7x.pt --source C:\Users\Administrator\Desktop\Yolov7-Close-People-Counter\inference\images\bus.jpg --distance_rate 170 --no-trace
Namespace(weights=['/content/Yolov7-Close-People-Counter/weights/yolov7x.pt'], source='C:\\Users\\Administrator\\Desktop\\Yolov7-Close-People-Counter\\inference\\images\\bus.jpg', img_size=640, conf_thres=0.25, iou_thres=0.45, device='', view_img=False, save_txt=False, save_conf=False, nosave=False, classes=None, agnostic_nms=False, augment=False, update=False, project='runs/detect', name='exp', distance_rate=170, exist_ok=False, no_trace=True)
YOLOR  2c6a8e2 torch 1.12.1+cpu CPU

Fusing layers...
Model Summary: 354 layers, 71311741 parameters, 571965 gradients
C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\functional.py:478: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  ..\aten\src\ATen\native\TensorShape.cpp:2895.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
C:\Users\Administrator\Desktop\Yolov7-Close-People-Counter\detect.py:189: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  m = torch.tensor(i-j).unsqueeze(0)
4 persons, 1 bicycle, 1 bus, 1 handbag, 1 tie, Done. (1515.4ms) Inference, (15.5ms) NMS
 The image with the result is saved in: runs\detect\exp9\bus.jpg
Done. (1.625s)
```

**Comment by bbartling** [comment]
wow this is rad.... using `--source 0` the USB cam works just fine

![image](https://user-images.githubusercontent.com/29737117/190224423-80208476-e981-469a-a2ed-2f87a837b907.png)

I can tell its a bit laggy but super cool

**Comment by DoganK01** [comment]
@bbartling Hey, This is the demo version. I suggest you try the latest version on my Github page.

**Comment by bbartling** [comment]
Any chance you can send me a link for how to use that? I cant tell which repo I should use.....my only use case is close up people counting

**Comment by DoganK01** [comment]
https://github.com/DoganK01/YOLOV7-OBJECT-COUNTER-V1.2

There is no counting in new version, but you can get visual results and you can get better results in terms of close people counting. In the old version, you can get better results for different images by changing the distance_rate variable as you want. In the new version, I set a certain distance_rate, but it changes according to human sizes. Your choice. In the new version, you can add the counter by making minor changes in the code I wrote.

Also, I just made a change in the old version (the version you are using). I recommend replacing it:
![image](https://user-images.githubusercontent.com/98788987/190230795-c9bfa2ca-0b11-4d7c-bc7f-b3619f7a9ff5.png)

**Comment by DoganK01** [comment]
This project is just for counting, but the new project is to visually understand which ones are close.

**Comment by DoganK01** [comment]
Also, the other model gives better performance.

**Comment by bbartling** [comment]
Okay ill jump to that new version but sort of having fun with this for the moment....any chance you could reiterate how this should be modified?

`cv2.putText(im0,f"Close People: = {close_people - people_len}",(0, 300), cv2.FONT_HERSHEY_TRIPLEX,1, (0, 0, 0), 1)`

**Comment by DoganK01** [comment]
I think delete the files you downloaded and download the new version. This is the demo version and does not provide any visual information. Also, the accuracy of the other model is higher.

**Comment by DoganK01** [comment]
If you want a counter in the new version, I'll send you a modified one. It's enough to write.

**Comment by DoganK01** [comment]
I am adding a counter file to the new version. Whichever you want to run. The decision is yours.

**Comment by DoganK01** [comment]
@bbartling Now you can download the new file from the link I gave. If you run counter.py you will get the counter you want. If you run detect.py you will get a visual description.

**Comment by bbartling** [comment]
Thanks for the links and responding the git issue right away....ill switch over to the new repo/code that you sent me:

Would you recommend me to try one Vs the other for close up people counting?

![image](https://user-images.githubusercontent.com/29737117/190239697-b05921fb-6d24-4a93-8b1b-ffb3e2d0f37a.png)

**Comment by DoganK01** [comment]
It doesn't matter what weight you take. If you follow the instructions, you will get what you want.

**Comment by bbartling** [comment]
Great thanks!
